### ISSUE TITLE
语法分析的第一条思路我喜欢

### ISSUE THREAD

**Issue by kenpusney** [esrever10/freeCompute#3]
代码呢？

---

@ellochen 
就是把常规的表达式编译成Lisp形式，然后再求值。
那为什么不直接就用用S-exp？

**Comment by esrever10** [comment]
噗 = =正要写呢= = README 只是我计划要写的东西= =

**Comment by esrever10** [comment]
@kenpusney 话说 大神 第一种思路 不是最基本的么?  一般数据结构书上都是这么搞= =中转后 再计算... 这块不清楚最好的方式是什么暂时就想到这两个思路,至于S-exp, 我无知没有学过类Lisp语言,但这在我的学习计划之内.  最近需要学Obj-C.

**Comment by kenpusney** [comment]
@ellochen 嗯，Objective-C值得一学，特别是从Smalltalk那里继承来的部分。

其实我也不太清楚哪种是最基本的方式。看过编译原理是要先转换成AST然后再求值，但总感觉前缀表达式要更简单直观一点吧。

**Comment by esrever10** [comment]
@kenpusney lisp那种形式真是简单的很彻底,  待我学习的时候也打算写一个简单的lisp解释器之类,  不过现在,编译原理还木有仔细学过,先用计算器练练手= =  要学obj-c是因为可能要做ios的项目, 时间拙计,好难分配= =
