### ISSUE TITLE
推荐的一本不错的在线书籍

### ISSUE THREAD

**Issue by kenpusney** [esrever10/freeCompute#4]
http://cs.brown.edu/~sk/Publications/Books/ProgLangs/

**Comment by esrever10** [comment]
@kenpusney tks~  mark了， 我这两天在看《编程语言实现模式 》也很有启发  没想到可以编程自动根据文法生成语法词法解析器

**Comment by kenpusney** [comment]
@ellochen 
典型的有lex+yacc套件（现在的替代品是flex+bison）和ANTLR
但是还是有很多人坚持手写parser的
比如PUC-Rio的Lua

**Comment by esrever10** [comment]
@kenpusney 很有意思，学习了~
